version: '3.7'

services:
  redis:
    image: redis
#    networks:
#      - redis
  web:
    image: kpeiruza/docker-php-mysql-redis
#    networks:
#      - redis
#      - proxy
#   deploy:
#      labels:
#        traefik.port: 8080
#        traefik.frontend.rule: 'Host:webapp.192.168.20.221.nip.io'
#        traefik.docker.network: 'proxy'
    ports:
      - 8000:80
#networks:
#  redis:
#    driver: 'overlay'
#  proxy:
#    external: true



